# Generated by Django 4.2 on 2023-05-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='image',
            field=models.ImageField(default=1, upload_to='amenities'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='dis_four',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='dis_one',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='dis_three',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='dis_two',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='title_four',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='title_one',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='title_three',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='title_two',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('U', 'UNDER_CONSTRUCTION'), ('N', 'NEW_LUNCH'), ('R', 'READY_MOVE')], max_length=1),
        ),
    ]
